In [0]:
!pip freeze

In [0]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.14.0


In [0]:
hello = tf.constant("Hello ")

In [0]:
world = tf.constant("world")

In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [8]:
print(result)

b'Hello world'


In [0]:
const = tf.constant(10)

In [0]:
fill_mat = tf.fill((4,4), 10)

In [0]:
myzeros = tf.zeros((4,4))

In [0]:
myones = tf.ones((4,4))

In [0]:
myrand = tf.random_normal((4,4), mean=0, stddev=1)

In [0]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [0]:
myops = [const, fill_mat, myzeros, myones, myrand, myrandu]

In [0]:
sess = tf.InteractiveSession()

In [21]:
for op in myops:
  print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.4207596   0.57517177  0.9050874   1.8585614 ]
 [ 1.0718437  -1.9158711   1.628685   -3.5386248 ]
 [-0.8564894  -2.0680203   1.715177    0.44072446]
 [-1.1106331   0.77696186  1.4667469   0.5544145 ]]
[[0.74996245 0.0495038  0.21142244 0.4395237 ]
 [0.25173593 0.9605726  0.72194266 0.5920838 ]
 [0.2236116  0.57801175 0.8633367  0.18621981]
 [0.11255527 0.76120925 0.6633159  0.29844344]]


In [0]:
a = tf.constant([
    [1,2],
    [3,4]
])

In [23]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([[10], [100]])

In [26]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a,b)

In [28]:
sess.run(result)

array([[210],
       [430]], dtype=int32)